#test:
#  service: Disk
#  root: <%#= Rails.root.join("tmp/storage") %>

#local:
#  service: S3
#  root: <%#= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

  amazon:
    service: S3
    access_key_id: <%= ENV['AWS_BUCKET_PIXIES_ACCESS_KEY_PUBLIC'] %>
    secret_access_key: <%= ENV['AWS_BUCKET_PIXIES_SECRET_ACCESS_KEY_PUBLIC'] %>
    bucket: <%= ENV['AWS_BUCKET_PIXIES_NAME_PUBLIC'] %>
    region: <%= ENV['AWS_BUCKET_PIXIES_REGION_PUBLIC'] %>